window.SEE_ONBOARDING_FLOW = (() => {
  const assetBase = window.SEE_FLOW_ASSET_BASE || "assets";
  const image = (name) => `${assetBase}/images/${name}`;

  return {
    impactCarouselCount: 5,
    assets: {
      background: image("background_yellow.png"),
      lineChart: image("line_chart.png"),
      onOffSwitch: image("on-off_switch.png"),
      lifeBenefitsArc: image("life_benefits_arc.png"),
      champagneToast: image("champagne_toast_3.png?v=20260619-1322"),
      letGoHand: image("let_go_hand_outline.png?v=20260619-1322"),
      moon: image("moon.png?v=20260619-1524"),
      lightningBolt: image("lightning_bolt_2.png?v=20260619-1537"),
    },
    screens: {
      welcome: {
        headline: "Get your life back from alcohol.",
        body: "If drinking is taking too much from you, you’re in the right place.",
        button: "continue",
      },
      goal: {
        headlineLines: ["Which", "are you?"],
        choices: [
          {
            goal: "less",
            label: "I want to drink less",
            imageKey: "lineChart",
          },
          {
            goal: "stop",
            label: "I want to stop entirely",
            imageKey: "onOffSwitch",
          },
        ],
      },
      benefits: {
        branchLabel: "Stop entirely path",
        headline: "A life without alcohol changes a lot about you",
        headlineClass: "compact",
        imageKey: "lifeBenefitsArc",
        imageClass: "benefits-art",
        body: [
          "You’ll sleep better, have more energy, and can repair relationships with loved ones.",
          "You’ll think more clearly, focus better, and experience improved memory, too.",
        ],
        button: "continue",
      },
      social: {
        branchLabel: "Drink less path",
        headline: "That is great.",
        headlineClass: "medium",
        imageKey: "champagneToast",
        imageClass: "toast-art",
        body: [
          "Alcohol is a powerful social lubricant. Parties, celebrations, events with friends and family.",
          "Drink responsibly — just less often, with less brain fog, less regret, and better health.",
        ],
        button: "continue",
      },
      willpower: {
        headline: "But It’s Not About Willpower",
        headlineClass: "medium",
        imageKey: "letGoHand",
        imageClass: "willpower-art",
        body: ["Trying harder doesn’t always work, but you can access the power of choice."],
        button: "Let’s find that!",
      },
      downsides: {
        title: "What is Alcohol Costing You?",
        subtitle: "Pick all that apply.",
        options: [
          "It affects my physical health negatively",
          "I’m tired of bad mornings",
          "Too much brain fog",
          "My overall energy levels are lower",
          "My sleep quality suffers",
          "Too much anxiety, shame, or regret",
          "Alcohol is taking up too much space in my life",
          "I need to lose weight",
          "Relationships with friends and family are suffering",
          "My work, productivity, or reputation is suffering",
          "Drinking has become too automatic",
          "Too much lost time",
          "Low mood after drinking",
        ],
        button: "continue",
      },
      drinks: {
        headline: "In a typical week, how many alcoholic drinks do you have?",
        options: ["0", "1–3", "4–7", "8–14", "15–24", "25–49", "50+"],
        button: "continue",
      },
      grip: {
        headline: "When alcohol’s grip slips, things start to get better...",
        headlineClass: "medium",
        button: "continue",
      },
      sleep: {
        headline: "Get a Better Night’s Sleep",
        headlineClass: "medium",
        imageKey: "moon",
        imageClass: "moon-art",
        body: ["Your sleep cycles improve. A better chance to rest, recover and reset."],
        button: "continue",
        progressIndex: 0,
      },
      energy: {
        headline: "Have More Energy",
        headlineClass: "medium",
        imageKey: "lightningBolt",
        imageClass: "bolt-art",
        body: ["Fewer sluggish mornings and days. Less hours wasted and more power for the day"],
        button: "continue",
        progressIndex: 1,
      },
      focus: {
        headline: "Focus On What’s Important",
        headlineClass: "medium",
        imageClass: "placeholder-art",
        placeholder: true,
        body: ["Attention comes back online. Finish tasks after you start them. Get things done faster."],
        button: "continue",
        progressIndex: 2,
      },
      memory: {
        headline: "Sharper Memory",
        headlineClass: "medium",
        imageClass: "placeholder-art",
        placeholder: true,
        body: ["Brain Fog Lifts. Experience better recall and an increased sense of confidence."],
        button: "continue",
        progressIndex: 3,
      },
      relationships: {
        headline: "Relationships Improve",
        headlineClass: "medium",
        imageClass: "placeholder-art",
        placeholder: true,
        body: [
          "Experience more patience and freedom from anger, allowing relationships with family, friends, and loved ones to heal.",
        ],
        button: "continue",
        progressIndex: 4,
      },
    },
    overview: [
      { screen: "welcome", label: "1" },
      { screen: "goal", label: "2" },
      { screen: "social", label: "3A · Drink less" },
      { screen: "benefits", label: "3B · Stop entirely" },
      { screen: "willpower", label: "4" },
      { screen: "downsides", label: "5" },
      { screen: "drinks", label: "6" },
      { screen: "grip", label: "8A" },
      { screen: "sleep", label: "8B" },
      { screen: "energy", label: "8C" },
      { screen: "focus", label: "8D" },
      { screen: "memory", label: "8E" },
      { screen: "relationships", label: "8F" },
    ],
  };
})();
